### ISSUE TITLE
error in prior

### ISSUE THREAD

**Issue by pioneer-innovation** [allenai/prior#11]
Hi @mattdeitke ,
I use the demo code below to get procthor-10k, but it returns error below.

**code:**
```python
import prior
prior.load_dataset("procthor-10k")
```

**error:**

    Loading train:   0%|          | 0/10000 [00:00<?, ?it/s]
    Traceback (most recent call last):
      File "/home/casia/experiment/AI2THOR/down.py", line 2, in <module>
        prior.load_dataset("procthor-10k")
      File "/home/casia/anaconda3/envs/AI2THOR/lib/python3.9/site-packages/prior/__init__.py", line 247, in load_dataset
        out_dataset: DatasetDict = out["load_dataset"](**params)
      File "<string>", line 44, in load_dataset
      File "<string>", line 44, in <listcomp>
      File "/home/casia/anaconda3/envs/AI2THOR/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
        for obj in iterable:
      File "/home/casia/anaconda3/envs/AI2THOR/lib/python3.9/gzip.py", line 398, in readline
        return self._buffer.readline(size)
      File "/home/casia/anaconda3/envs/AI2THOR/lib/python3.9/_compression.py", line 68, in readinto
        data = self.read(len(byte_view))
      File "/home/casia/anaconda3/envs/AI2THOR/lib/python3.9/gzip.py", line 487, in read
        if not self._read_gzip_header():
      File "/home/casia/anaconda3/envs/AI2THOR/lib/python3.9/gzip.py", line 435, in _read_gzip_header
        raise BadGzipFile('Not a gzipped file (%r)' % magic)
    gzip.BadGzipFile: Not a gzipped file (b've')

**Comment by mattdeitke** [comment]
Can you describe your machine setup?

**Comment by pioneer-innovation** [comment]
Linux version 5.4.0-107-generic (buildd@lcy02-amd64-070) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022

**Comment by mattdeitke** [comment]
Can you show me what you get when you run:
```
ls ~/.prior/datasets/allenai/procthor-10k/d54954a81e7126001e552c2d7904ee2e0d49eaae
```
and
```
cat ~/.prior/datasets/allenai/procthor-10k/d54954a81e7126001e552c2d7904ee2e0d49eaae/train.jsonl.gz | head -n 500
```

**Comment by pioneer-innovation** [comment]
![Screenshot from 2022-07-15 13-48-31](https://user-images.githubusercontent.com/54060693/179159550-0ebe39ec-246e-46d9-9b54-6e73532f1f80.png)

**Comment by mattdeitke** [comment]
Thanks! It looks like our workaround for Git LFS is not working. Let me check with @Lucaweihs on this.

**Comment by mattdeitke** [comment]
Can you also run:

```python
import prior
print(prior.version.VERSION)
```
This will just show us if it's using the expected version :)

**Comment by pioneer-innovation** [comment]
It return error:

    Traceback (most recent call last):
      File "/home/casia/experiment/AI2THOR/down.py", line 2, in <module>
        print(prior.version.VERSION)
    AttributeError: module 'prior' has no attribute 'version'

**Comment by mattdeitke** [comment]
Ah, sorry. Can you run:
```
import prior.version
print(prior.version.VERSION)
```

**Comment by pioneer-innovation** [comment]
It returns:

    0.0.1.dev21

**Comment by mattdeitke** [comment]
👍 Thanks! Hopefully should have something soon.

**Comment by pioneer-innovation** [comment]
Good luck!

**Comment by Lucaweihs** [comment]
@mattdeitke Isn't `0.0.1.dev21` the version before the git-lfs fix? @pioneer-innovation can you try upgrading to the newest version (`0.0.1.dev24`), removing `~/.prior/datasets/allenai/procthor-10k`, and trying again?

**Comment by mattdeitke** [comment]
Ah, you could be right. The version on my machine was 0.0.1.dev21, so I thought that was the latest. Yes, please try that!

**Comment by Lucaweihs** [comment]
I'm going to close this issue @pioneer-innovation, feel free to reopen if the above didn't fix your issue.
