### ISSUE TITLE
Prior package is not found via pip

### ISSUE THREAD

**Issue by mariiak2021** [allenai/prior#16]
Hi!
Some days ago I was able to successfully install prior package using pip, but unfortunately since yesterday it's not available any more.

pip install prior
ERROR: Could not find a version that satisfies the requirement prior (from versions: none)
ERROR: No matching distribution found for prior

Can you provide any suggestions or ideas? Thanx!

**Comment by mattdeitke** [comment]
Hmm, can you try updating your version of pypi?

**Comment by mariiak2021** [comment]
Hi @mattdeitke 
It worked today again without any update. Not sure what was the problem - perhaps, some temporary issues.
Thank you!
