### ISSUE TITLE
Not able to load houses using prior

### ISSUE THREAD

**Issue by Bnjorogedev** [allenai/prior#17]
## Checklist

- [x] I have verified that the issue exists against the `main` branch.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/prior/blob/main/CONTRIBUTING.md#bug-reports-and-feature-requests) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/prior/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/prior/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/prior/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/prior/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

I am trying to load ProctHor's datasets using prior but can't be able to. 

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import prior
  File "/home/bnjoroge/.local/lib/python3.8/site-packages/prior/__init__.py", line 18, in <module>
    from prior.utils.types import  DatasetDict
  File "/home/bnjoroge/.local/lib/python3.8/site-packages/prior/utils/types.py", line 10, in <module>
    from attr import field
ImportError: cannot import name 'field' from 'attr' (/usr/lib/python3/dist-packages/attr/__init__.py)
```
The "field" value is not importable from "attr" and when I traced back to the source it wasn't defined as well. Am I missing something? 

I also wasn't able to import the define dcorator. 
</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS:
WSL Ubuntu

Python version:
Python 3.8.1
<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
opencv-python==4.6.0.66
packaging==21.3
pandas==1.4.2
parameterized==0.8.1
parso==0.8.3
pathspec==0.9.0
pep517==0.12.0
pexpect==4.6.0
pickleshare==0.7.5
Pillow==9.2.0
pkginfo==1.8.2
platformdirs==2.5.2
pluggy==1.0.0
portalocker==2.5.1
prior==1.0.0
proglog==0.1.10
progressbar2==4.0.0
prompt-toolkit==3.0.29
protobuf==3.19.4
psutil==5.9.1
pure-eval==0.2.2
py==1.11.0
pyarrow==4.0.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycocotools==2.0.4
pycodestyle==2.8.0
pycosat==0.6.3
pycparser==2.21
pycups==1.9.73
pydantic==1.9.1
pydocstyle==6.1.1
pydot==1.4.2
pyflakes==2.4.0
PyGithub==1.55
Pygments==2.12.0
PyGObject==3.36.0
PyHamcrest==1.9.0
PyHive==0.6.5
PyJWT==2.4.0
pymacaroons==0.13.0
PyNaCl==1.5.0
pyOpenSSL==19.0.0
pyparsing==3.0.9
pyRFC3339==1.1
pyrsistent==0.15.5
pyserial==3.4
PySocks==1.7.1
pytest==7.1.2
pytest-cov==3.0.0
pytest-mock==3.7.0
python-apt==2.0.0+ubuntu0.20.4.5
python-dateutil==2.8.2
python-debian===0.1.36ubuntu1
python-utils==3.3.3
python-xlib==0.31
pytz==2022.1
PyYAML==5.3.1
pyzmq==23.2.0
readme-renderer==35.0
regex==2022.7.25
requests==2.22.0
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
requests-unixsocket==0.2.0
retrying==1.3.3
rfc3986==2.0.0
rich==12.4.4
rsa==4.8
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
s3transfer==0.6.0
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
service-identity==18.1.0
setuptools-scm==6.4.2
simplejson==3.16.0
six==1.14.0
snowballstemmer==2.2.0
sos==4.1
soupsieve==2.3.2.post1
Sphinx==5.0.0
sphinx-rtd-theme==1.0.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
ssh-import-id==5.10
stack-data==0.2.0
systemd-python==234
tabulate==0.8.10
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
termcolor==1.1.0
testfixtures==6.18.5
timm==0.6.7
toml==0.10.2
tomli==2.0.1
torch==1.10.1+cu111
torch-tb-profiler==0.4.0
torchaudio==0.12.1
torchvision==0.11.2+cu111
tornado==6.2
tqdm==4.64.0
traitlets==5.2.2.post1
twine==4.0.0
Twisted==18.9.0
typing-extensions==4.2.0
ubuntu-advantage-tools==27.2
ufw==0.36
unattended-upgrades==0.1
urllib3==1.26.9
virtualenv==20.14.1
wadllib==1.3.3
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.2.1
wrapt==1.14.1
xkit==0.0.0
yacs==0.1.8
zipp==3.8.1
zope.interface==4.7.1
```

</p>
</details>

## Steps to reproduce
pip install ai2thor, and the dependencies. 
Then try to load houses using the load_dataset() method. 

<details>
<summary><b>Example source:</b></summary>
<p>

```
pip install --extra-index-url https://ai2thor-pypi.allenai.org ai2thor==0+391b3fae4d4cc026f1522e5acf60953560235971 &> /dev/null
!pip install ai2thor-colab prior --upgrade &> /dev/null

pip install --extra-index-url https://ai2thor-pypi.allenai.org ai2thor==0+391b3fae4d4cc026f1522e5acf60953560235971 &> /dev/null
!pip install ai2thor-colab prior --upgrade &> /dev/null
```

</p>
</details>

**Comment by Bnjorogedev** [comment]
Would appreciate thoughts on what I might be missing.

**Comment by Bnjorogedev** [comment]
Had a lot of dependency collision issues because I wasn't using a virtual environment but reinstalled in a virtual environment and worked. gonna close this issue

**Comment by mattdeitke** [comment]
Sorry about that @Bnjorogedev, not totally sure what the issue was, looks like it had something to do with the attrs package. Glad you were able to resolve it!
